        <div>
            <h1>Maruchan</h1>
            <p>Labore pariatur tempor ipsum qui sit cupidatat id nulla dolor adipisicing anim sit exercitation. Ipsum
                fugiat exercitation do in anim esse deserunt. Incididunt aliqua irure sunt irure velit sunt Lorem
                ullamco cupidatat officia. Officia veniam sunt consectetur qui occaecat. Aliqua anim tempor est qui
                labore magna mollit eiusmod ad commodo occaecat amet laborum non.
            </p>
        </div>